### ISSUE TITLE
Triaging slowness 

### ISSUE THREAD

**Issue by m-rit** [shweta-kumaran/CastNXTfall24#68]

**Comment by rahulb99** [comment]
Description
----
Application https://castnxtfall2024-a6422e600193.herokuapp.com loads very slowly when browsing it after X time. 

Task
----
Investigate the slowness and provide possible solutions

**Comment by rahulb99** [comment]
There are primarily 2 reasons, which together, make the loading times painfully slow:
* The app is running on [Heroku Eco Dynos](https://devcenter.heroku.com/articles/eco-dyno-hours)
> If an app has an Eco web dyno, and that dyno receives no web traffic in a 30-minute period, it sleeps. In addition to the web dyno sleeping, if you have a worker Eco dyno, it also sleeps.
* The app is using React for front-end with [webpacker](https://github.com/rails/webpacker) for JS bundling & compilation. This step is slow (and increases the Docker image size quite a lot) since we are using many React components.

 Possible solutions:
* Switch to [Basic Dynos](https://devcenter.heroku.com/articles/eco-dyno-hours#managing-your-eco-dyno-usage)
* Optimize webpack configuration (remove intermediate files from Docker image, use production mode, remove any development dependencies for production app)
